version: "3"

services:
  db:
    build: ./postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_MULTIPLE_DATABASES: todo,todo_test
    ports:
      - "5432:5432"